name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: |
          pytest

      - name: Build the Docker image
        run: docker build . --tag arielxx/devops_exam:latest

      - name: Docker login}}
        run: docker login --username arielxx --password ${{ secrets.DOCKER_PASSWORD}}

      - name: Docker push
        run: docker push arielxx/devops_exam:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Run Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: 10.10.50.3
          username: vagrant
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker run -d -p 9093:9093 arielxx/devops_exam:latest
